import { INFINI2_WASM_BASE64 } from "./generated/wasm-bytes";

let compiledModule: WebAssembly.Module | null = null;
let sharedInstance: WebAssembly.Instance | null = null;

function decodeBase64(value: string): Uint8Array {
  if (!value) {
    throw new Error(
      "Infini2 Wasm has not been built; run npm run infini2:build",
    );
  }
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

/**
 * Returns the process-wide compiled, import-free Infini2 Wasm module.
 *
 * @throws If generated bytes are missing or WebAssembly compilation fails.
 * @advanced Prefer `Infini2Controller` in application code.
 */
export function getInfini2WasmModule(): WebAssembly.Module {
  compiledModule ??= new WebAssembly.Module(
    decodeBase64(INFINI2_WASM_BASE64).buffer as ArrayBuffer,
  );
  return compiledModule;
}

/**
 * Returns the process-wide shared Wasm instance used by all raw engines.
 * @advanced Engine heap objects remain isolated by their numeric pointer.
 */
export function getInfini2WasmInstance(): WebAssembly.Instance {
  sharedInstance ??= new WebAssembly.Instance(getInfini2WasmModule(), {});
  return sharedInstance;
}

/**
 * Returns the shared instance exports cast to an executor-owned ABI interface.
 * @advanced Callers must validate ABI version before invoking raw functions.
 */
export function getInfini2WasmExports<T extends WebAssembly.Exports>(): T {
  return getInfini2WasmInstance().exports as T;
}
