import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const infiniDirectory = path.resolve(scriptDirectory, "..");
const rustDirectory = path.join(infiniDirectory, "rust");
const releaseDirectory = path.join(
  rustDirectory,
  "target",
  "wasm32-unknown-unknown",
  "release",
);
const generatedDirectory = path.join(infiniDirectory, "runtime", "generated");
const generatedModule = path.join(generatedDirectory, "wasm-bytes.ts");
const cargo = process.platform === "win32" ? "cargo.exe" : "cargo";
const wasmRustflags = [process.env.RUSTFLAGS, "-Ctarget-cpu=mvp"]
  .filter(Boolean)
  .join(" ");

const build = spawnSync(
  cargo,
  [
    "+nightly-2026-05-10",
    "build",
    "--locked",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "-Zbuild-std=panic_abort,std",
  ],
  {
    cwd: rustDirectory,
    encoding: "utf8",
    stdio: "inherit",
    env: { ...process.env, RUSTFLAGS: wasmRustflags },
  },
);
if (build.error) throw build.error;
if (build.status !== 0) process.exit(build.status ?? 1);

const candidates = readdirSync(releaseDirectory)
  .filter((file) => file.endsWith(".wasm"))
  .sort();
if (candidates.length !== 1) {
  throw new Error(
    `Expected one Infini2 Wasm artifact, found: ${candidates.join(", ") || "none"}`,
  );
}

const wasm = readFileSync(path.join(releaseDirectory, candidates[0]));
if (
  wasm.length < 8 ||
  wasm[0] !== 0x00 ||
  wasm[1] !== 0x61 ||
  wasm[2] !== 0x73 ||
  wasm[3] !== 0x6d
) {
  throw new Error("Infini2 Rust build did not produce valid WebAssembly");
}

const module = new WebAssembly.Module(wasm);
const imports = WebAssembly.Module.imports(module);
if (imports.length > 0) {
  throw new Error(
    `Infini2 Wasm must have no imports: ${imports
      .map((entry) => `${entry.module}.${entry.name}`)
      .join(", ")}`,
  );
}
new WebAssembly.Instance(module, {});

const source =
  "// Generated by lib/infini2/scripts/build-wasm.mjs. Do not edit.\n" +
  `export const INFINI2_WASM_BASE64 = ${JSON.stringify(wasm.toString("base64"))};\n`;
mkdirSync(generatedDirectory, { recursive: true });
let previous = "";
try {
  previous = readFileSync(generatedModule, "utf8");
} catch {
  // First build.
}
if (source !== previous) writeFileSync(generatedModule, source);

console.log(
  `Infini2 Wasm: ${candidates[0]} (${wasm.length.toLocaleString()} bytes, inlined)`,
);
